### ISSUE TITLE
Update to shariff v3.2.1

### ISSUE THREAD

**Issue by tobiasherp** [collective/collective.shariff#3]
Currently (in v1.0) we have shariff 2.1.1 (2018-01-19), which is outdated (e.g still containing googleplus);
we should update to v3.2.1 (2019-05-27, the currently most recent version).

**Comment by tobiasherp** [comment]
@petschki Could you make a new release, please?
@fredvd @ale-rt I added a contributors file. Would it be ok to use your full names there? (without e-mail)

**Comment by petschki** [comment]
If you give me your pypi handle, I'll add you as maintainer

**Comment by fredvd** [comment]
@tobiasherp no problem for me

**Comment by tobiasherp** [comment]
@petschki That would be visaplan

**Comment by petschki** [comment]
sent you an invite

**Comment by tobiasherp** [comment]
@petschki We have a release 1.1.a1 now.
